# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - m2mclothingtanloc

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://m2mcolthing.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_4d906c96310b445babde8a159dacf115 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_13dcec2543864d1cbe6599d86b0833c2 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: m2mcolthing.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_4d906c96310b445babde8a159dacf115 }}/m2mcolthing:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'm2mclothingtanloc'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_63685812495d4fb38049c5f5bb46e10b }}
        images: 'm2mcolthing.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_4d906c96310b445babde8a159dacf115 }}/m2mcolthing:${{ github.sha }}'