# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - m2mclothingtanloc

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://m2mcolthing.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_e95af465bf474b828a72cf90feee2a9b }}
        password: ${{ secrets.AzureAppService_ContainerPassword_645c9859fcfa4297947056676ce75290 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: m2mcolthing.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_e95af465bf474b828a72cf90feee2a9b }}/m2mcolthing:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'm2mclothingtanloc'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_c585c9b698f84810b908601c61152ddd }}
        images: 'm2mcolthing.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_e95af465bf474b828a72cf90feee2a9b }}/m2mcolthing:${{ github.sha }}'